version: 2.1
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: cimg/node:18.12.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: rails

      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: josh
          POSTGRES_PASSWORD: null

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: set up database
          command: |
            yarn seq db:migrate --env=test

      - run:
          name: run tests
          command: yarn test:ci

workflows:
  test-workflow:
    jobs:
      - test
